// <auto-generated />
using System;
using Legi.Library.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legi.Library.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260314191209_InitialLibrarySchema")]
    partial class InitialLibrarySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legi.Library.Domain.Entities.BookSnapshot", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<string>("AuthorDisplay")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("author_display");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_url");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("BookId");

                    b.ToTable("book_snapshots", (string)null);
                });

            modelBuilder.Entity("Legi.Library.Domain.Entities.ReadingPost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<int>("CommentsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("comments_count");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LikesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("likes_count");

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("date")
                        .HasColumnName("reading_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserBookId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_book_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserBookId")
                        .HasDatabaseName("ix_reading_posts_user_book_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reading_posts_user_id");

                    b.HasIndex("UserBookId", "ReadingDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_reading_posts_user_book_date");

                    b.ToTable("reading_posts", (string)null);
                });

            modelBuilder.Entity("Legi.Library.Domain.Entities.UserBook", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("WishList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("wishlist");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_books_user_id");

                    b.HasIndex("UserId", "BookId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_books_user_book")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("user_books", (string)null);
                });

            modelBuilder.Entity("Legi.Library.Domain.Entities.UserList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BooksCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("books_count");

                    b.Property<int>("CommentsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("comments_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public");

                    b.Property<int>("LikesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("likes_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("ix_user_lists_is_public")
                        .HasFilter("is_public = true");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_lists_user_id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_user_lists_user_name");

                    b.ToTable("user_lists", (string)null);
                });

            modelBuilder.Entity("Legi.Library.Domain.Entities.UserListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("UserBookId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_book_id");

                    b.Property<Guid>("user_list_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("user_list_id", "Order")
                        .HasDatabaseName("ix_user_list_items_list_order");

                    b.HasIndex("user_list_id", "UserBookId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_list_items_list_book");

                    b.ToTable("user_list_items", (string)null);
                });

            modelBuilder.Entity("Legi.Library.Domain.Entities.ReadingPost", b =>
                {
                    b.OwnsOne("Legi.Library.Domain.ValueObjects.Progress", "CurrentProgress", b1 =>
                        {
                            b1.Property<Guid>("ReadingPostId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("progress_type");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("progress_value");

                            b1.HasKey("ReadingPostId");

                            b1.ToTable("reading_posts");

                            b1.WithOwner()
                                .HasForeignKey("ReadingPostId");
                        });

                    b.Navigation("CurrentProgress");
                });

            modelBuilder.Entity("Legi.Library.Domain.Entities.UserBook", b =>
                {
                    b.OwnsOne("Legi.Library.Domain.ValueObjects.Progress", "CurrentProgress", b1 =>
                        {
                            b1.Property<Guid>("UserBookId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("progress_type");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("progress_value");

                            b1.HasKey("UserBookId");

                            b1.ToTable("user_books");

                            b1.WithOwner()
                                .HasForeignKey("UserBookId");
                        });

                    b.OwnsOne("Legi.Library.Domain.ValueObjects.Rating", "CurrentRating", b1 =>
                        {
                            b1.Property<Guid>("UserBookId")
                                .HasColumnType("uuid");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("rating_value");

                            b1.HasKey("UserBookId");

                            b1.ToTable("user_books");

                            b1.WithOwner()
                                .HasForeignKey("UserBookId");
                        });

                    b.Navigation("CurrentProgress");

                    b.Navigation("CurrentRating");
                });

            modelBuilder.Entity("Legi.Library.Domain.Entities.UserListItem", b =>
                {
                    b.HasOne("Legi.Library.Domain.Entities.UserList", null)
                        .WithMany("Items")
                        .HasForeignKey("user_list_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Legi.Library.Domain.Entities.UserList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
